### ISSUE TITLE
Order of the fixtures tab

### ISSUE THREAD

**Issue by jordanrzymski** [jordanrzymski/statmaster#4]
I think all the priority leagues should be elite leagues but keep the order they are in - I am current grouping but country in a test version and it Reorders the json - I can filter out the elite lists from the list I think

![image](https://user-images.githubusercontent.com/66678347/84311542-5c788f80-ab5b-11ea-94b3-f6ee8ea66288.jpeg)

**Comment by scrabble85** [comment]
Would it work better if I nested the JSON to separate out the elite leagues?

**Comment by jordanrzymski** [comment]
Yeah maybe every time I pass it though grouping or filtering in arrays there always performance issues - anything done server side is better

**Comment by scrabble85** [comment]
Ok will look into it
