### ISSUE TITLE
Notifications bombardment

### ISSUE THREAD

**Issue by cozy7126** [jordanrzymski/statmaster#6]
When users close the app, and re-open it hours later they get ALL previous notifications all in one

**Comment by jordanrzymski** [comment]
We need to work out what this actually is... notifications are notifications...

Are we talking about

In-app notifications 
Push-notifications 

If I turn my android phone off all day and turn it one I get every Facebook notification from the day.... causing bombardment which I can’t do nothing about

**Comment by cozy7126** [comment]
Think it’s the push notifications they were on about

But like tin said That’s an issue like FB and Twitter have & nothing u can do about it
